package com.trialsync.backend.nlp;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * The strict JSON schemas sent to Groq for patient and trial extraction.
 *
 * <p>Python derived these from the closed Pydantic models {@code _PatientPayload} and
 * {@code _TrialPayload} via {@code model_json_schema()} and then hardened them with
 * {@code _close_schema}, which sets {@code additionalProperties: false} on every object and promotes
 * every property to {@code required} - both mandatory for OpenAI-style {@code strict} structured
 * output.
 *
 * <p>They are written out literally here rather than reflected from Java classes, because the shape
 * a provider is constrained by is part of the wire contract: the {@code $defs}/{@code $ref} layout,
 * the {@code anyOf [type, null]} spelling of optional fields, the generated {@code title} values and
 * the alphabetical key order are all reproduced as Pydantic emitted them. A schema regenerated by a
 * different tool would constrain the model differently and change what it returns.
 *
 * <p>The bounds are load-bearing: {@code start >= 0}, {@code end >= 1} and a 2,000 character quote
 * limit are what let {@code GroqExtractor} verify every quotation against the real page text.
 */
public final class ExtractionSchemas {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private static final String PATIENT_SCHEMA_JSON =
            """
            {
              "$defs": {
                "_PatientFact": {
                  "additionalProperties": false,
                  "properties": {
                    "fact_type": {"title": "Fact Type", "type": "string"},
                    "concept": {"title": "Concept", "type": "string"},
                    "value_numeric": {
                      "anyOf": [{"type": "number"}, {"type": "null"}],
                      "title": "Value Numeric"
                    },
                    "value_text": {
                      "anyOf": [{"type": "string"}, {"type": "null"}],
                      "title": "Value Text"
                    },
                    "unit": {"anyOf": [{"type": "string"}, {"type": "null"}], "title": "Unit"},
                    "assertion": {"title": "Assertion", "type": "string"},
                    "effective_date": {
                      "anyOf": [{"type": "string"}, {"type": "null"}],
                      "title": "Effective Date"
                    },
                    "source": {"$ref": "#/$defs/_Source"}
                  },
                  "required": [
                    "fact_type",
                    "concept",
                    "value_numeric",
                    "value_text",
                    "unit",
                    "assertion",
                    "effective_date",
                    "source"
                  ],
                  "title": "_PatientFact",
                  "type": "object"
                },
                "_Source": {
                  "additionalProperties": false,
                  "properties": {
                    "page": {"minimum": 1, "title": "Page", "type": "integer"},
                    "start": {"minimum": 0, "title": "Start", "type": "integer"},
                    "end": {"minimum": 1, "title": "End", "type": "integer"},
                    "text": {
                      "maxLength": 2000,
                      "minLength": 1,
                      "title": "Text",
                      "type": "string"
                    }
                  },
                  "required": ["page", "start", "end", "text"],
                  "title": "_Source",
                  "type": "object"
                }
              },
              "additionalProperties": false,
              "properties": {
                "display_name": {"title": "Display Name", "type": "string"},
                "date_of_birth": {
                  "anyOf": [{"type": "string"}, {"type": "null"}],
                  "title": "Date Of Birth"
                },
                "sex": {"anyOf": [{"type": "string"}, {"type": "null"}], "title": "Sex"},
                "facts": {
                  "items": {"$ref": "#/$defs/_PatientFact"},
                  "title": "Facts",
                  "type": "array"
                }
              },
              "required": ["display_name", "date_of_birth", "sex", "facts"],
              "title": "_PatientPayload",
              "type": "object"
            }
            """;

    private static final String TRIAL_SCHEMA_JSON =
            """
            {
              "$defs": {
                "_Source": {
                  "additionalProperties": false,
                  "properties": {
                    "page": {"minimum": 1, "title": "Page", "type": "integer"},
                    "start": {"minimum": 0, "title": "Start", "type": "integer"},
                    "end": {"minimum": 1, "title": "End", "type": "integer"},
                    "text": {
                      "maxLength": 2000,
                      "minLength": 1,
                      "title": "Text",
                      "type": "string"
                    }
                  },
                  "required": ["page", "start", "end", "text"],
                  "title": "_Source",
                  "type": "object"
                },
                "_TrialCriterion": {
                  "additionalProperties": false,
                  "properties": {
                    "kind": {"title": "Kind", "type": "string"},
                    "source_text": {"title": "Source Text", "type": "string"},
                    "normalized_rule_json": {
                      "anyOf": [{"type": "string"}, {"type": "null"}],
                      "title": "Normalized Rule Json"
                    },
                    "source": {"$ref": "#/$defs/_Source"}
                  },
                  "required": ["kind", "source_text", "normalized_rule_json", "source"],
                  "title": "_TrialCriterion",
                  "type": "object"
                }
              },
              "additionalProperties": false,
              "properties": {
                "title": {"title": "Title", "type": "string"},
                "condition": {"title": "Condition", "type": "string"},
                "phase": {"anyOf": [{"type": "string"}, {"type": "null"}], "title": "Phase"},
                "criteria": {
                  "items": {"$ref": "#/$defs/_TrialCriterion"},
                  "title": "Criteria",
                  "type": "array"
                }
              },
              "required": ["title", "condition", "phase", "criteria"],
              "title": "_TrialPayload",
              "type": "object"
            }
            """;

    private static final JsonNode PATIENT_SCHEMA = parse(PATIENT_SCHEMA_JSON);
    private static final JsonNode TRIAL_SCHEMA = parse(TRIAL_SCHEMA_JSON);

    private ExtractionSchemas() {}

    /** {@code _patient_schema()}. */
    public static JsonNode patientSchema() {
        return PATIENT_SCHEMA.deepCopy();
    }

    /** {@code _trial_schema()}. */
    public static JsonNode trialSchema() {
        return TRIAL_SCHEMA.deepCopy();
    }

    private static JsonNode parse(String json) {
        try {
            return MAPPER.readTree(json);
        } catch (JsonProcessingException exception) {
            throw new IllegalStateException("Extraction schema is not valid JSON", exception);
        }
    }
}
