package com.trialsync.backend.security;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;
import java.util.Base64;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import org.springframework.stereotype.Component;

/**
 * Byte-for-byte port of {@code trialsync.security.hash_password} / {@code verify_password}.
 *
 * <p>Stored format is {@code pbkdf2_sha256$600000$<salt>$<digest>} where both segments are
 * <em>padded</em> URL-safe Base64. The migration specification describes these as unpadded, but the
 * Python implementation uses {@code base64.urlsafe_b64encode} without stripping padding, so existing
 * password hashes carry the {@code =} characters. Behavioural compatibility with the running system
 * wins over the wording in the document; changing this would invalidate every stored credential.
 */
@Component
public class Pbkdf2PasswordHasher {

    public static final String ALGORITHM_LABEL = "pbkdf2_sha256";
    public static final int DEFAULT_ITERATIONS = 600_000;

    private static final int SALT_BYTES = 16;
    private static final int DERIVED_BITS = 256;
    private static final String SECRET_KEY_ALGORITHM = "PBKDF2WithHmacSHA256";

    private final SecureRandom random = new SecureRandom();

    /** Derives a fresh hash using a random 16-byte salt. */
    public String hash(String password) {
        byte[] salt = new byte[SALT_BYTES];
        random.nextBytes(salt);
        return encode(password, salt, DEFAULT_ITERATIONS);
    }

    /** Deterministic variant used by the compatibility tests. */
    public String encode(String password, byte[] salt, int iterations) {
        byte[] derived = pbkdf2(password, salt, iterations);
        Base64.Encoder encoder = Base64.getUrlEncoder();
        return ALGORITHM_LABEL
                + "$"
                + iterations
                + "$"
                + encoder.encodeToString(salt)
                + "$"
                + encoder.encodeToString(derived);
    }

    /**
     * Verifies a candidate password. Any malformed stored value returns {@code false} rather than
     * throwing, matching the Python {@code except (ValueError, TypeError)} guard.
     */
    public boolean verify(String password, String encoded) {
        if (password == null || encoded == null) {
            return false;
        }
        try {
            // Python uses split("$", 3), which yields exactly four segments and leaves any
            // additional "$" inside the final digest segment.
            String[] parts = splitLimit(encoded, '$', 4);
            if (parts.length != 4) {
                return false;
            }
            if (!ALGORITHM_LABEL.equals(parts[0])) {
                return false;
            }
            int iterations = Integer.parseInt(parts[1]);
            byte[] salt = decodeUrlBase64(parts[2]);
            byte[] expected = decodeUrlBase64(parts[3]);
            byte[] actual = pbkdf2(password, salt, iterations);
            return MessageDigest.isEqual(actual, expected);
        } catch (RuntimeException ex) {
            return false;
        }
    }

    private static byte[] pbkdf2(String password, byte[] salt, int iterations) {
        if (iterations <= 0) {
            throw new IllegalArgumentException("iteration count must be positive");
        }
        try {
            // PBEKeySpec takes a char[]; the JDK encodes it as UTF-8 for PBKDF2WithHmacSHA*,
            // which matches Python's password.encode() default of UTF-8.
            PBEKeySpec spec =
                    new PBEKeySpec(password.toCharArray(), salt, iterations, DERIVED_BITS);
            SecretKeyFactory factory = SecretKeyFactory.getInstance(SECRET_KEY_ALGORITHM);
            return factory.generateSecret(spec).getEncoded();
        } catch (NoSuchAlgorithmException | InvalidKeySpecException ex) {
            throw new IllegalStateException("PBKDF2-HMAC-SHA256 is unavailable", ex);
        }
    }

    /**
     * Decodes padded or unpadded URL-safe Base64. Python's {@code urlsafe_b64decode} requires
     * padding, and every hash this service writes carries it, but tolerating both keeps hashes
     * generated by other tooling verifiable.
     */
    private static byte[] decodeUrlBase64(String value) {
        String padded = value;
        int remainder = padded.length() % 4;
        if (remainder != 0) {
            padded = padded + "===".substring(0, 4 - remainder);
        }
        return Base64.getUrlDecoder().decode(padded.getBytes(StandardCharsets.US_ASCII));
    }

    /** Equivalent of Python's {@code str.split(sep, maxsplit)} with a fixed segment count. */
    private static String[] splitLimit(String value, char separator, int limit) {
        String[] result = new String[limit];
        int index = 0;
        int start = 0;
        while (index < limit - 1) {
            int next = value.indexOf(separator, start);
            if (next < 0) {
                return new String[0];
            }
            result[index++] = value.substring(start, next);
            start = next + 1;
        }
        result[index] = value.substring(start);
        return result;
    }
}
